### ISSUE TITLE
Artifacts not showing up in commit/pr page

### ISSUE THREAD

**Issue by seemethere** [pytorch/ci-hud#158]
<img width="804" alt="Screen Shot 2021-10-12 at 12 44 16 PM" src="https://user-images.githubusercontent.com/1700823/137004180-bebdd973-71f1-427c-becb-921773bfaab2.png">

Appears as though artifacts are not showing up on the commit/pr page where they previously were showing up

**Comment by driazati** [comment]
"useless" artifacts (https://github.com/pytorch/ci-hud/blob/main/src/PrDisplay.js#L829-L831) are filtered, I figured since people can see the test results inline they were just visual noise. we can revert that change if it's confusing

**Comment by driazati** [comment]
closing since this is mostly just a documentation problem but other users probably won't notice
