### ISSUE TITLE
iOS Safari is broken

### ISSUE THREAD

**Issue by driazati** [pytorch/ci-hud#192]
The status page doesn’t render and just shows a white screen, we’re probably missing some guards somewhere for browser APIs that aren’t on mobile (like `Notification`)

Using iOS + macbook safari to debug should be pretty simple, maybe we could also mock out the lack of APIs in our tests so too

**Comment by malfet** [comment]
This is due to https://github.com/pytorch/ci-hud/blob/28ec6a2160315fb838202f590eb13d6cadc24c13/src/pr/FailureReport.js#L36

Safari (as well as many other browsers do not support lookbehind/lookahead regexes)
